### ISSUE TITLE
License

### ISSUE THREAD

**Issue by julman99** [beluchin/decorice#3]
Hello!

First, thanks for this library!

Is it possible for you to add a license to this repo? 

Thanks a lot!

**Comment by beluchin** [comment]
hey, I'm glad is useful.

I have no idea what to do to add a license. Can you give me a couple of
pointers?

Thanks

**Comment by julman99** [comment]
Hi, you should add a `LICENSE` text file to your project. You can see for example, one of my projects: https://github.com/julman99/gson-fire, there is a LICENSE file.

I like to use the Apache 2.0 License, but some people use the MIT License (for example: https://github.com/vdurmont/emoji-java), and there are others you can choose from.

**Comment by julman99** [comment]
Hi there,

Just checking if you had a chance to look at this?

Thanks!

**Comment by beluchin** [comment]
Not yet. Will get to it this weekend

**Comment by beluchin** [comment]
done

**Comment by julman99** [comment]
Thanks a lot!
